### ISSUE TITLE
Appccelerate.DistributedEventBroker and MSMQ

### ISSUE THREAD

**Issue by achmedzhanov** [appccelerate/appccelerate#11]
Why did you implement distributed event broker for MSMQ? 
Are there any prombles with msmq architecture?

**Comment by ursenzler** [comment]
We didn't need it in one of our own projects yet. But you can write your own adapter for MSMQ and plug it into the event broker infrastructure. See here for details: http://www.appccelerate.com/distributedeventbrokercustomization.html.
And you can copy an existing implementation for starters.

Happy coding
Urs

**Comment by danielmarbach** [comment]
By default MassTransit, RhinoESB and also NServiceBus adapters use MSMQ underneath. Think twice before you implement it by yourself. For example MassTransit and RhinoESB are free of charge.

**Comment by danielmarbach** [comment]
@achmedzhanov is it OK if we close that issue?

**Comment by achmedzhanov** [comment]
Yes
