### ISSUE TITLE
question regarding StateMachine

### ISSUE THREAD

**Issue by noamberda** [appccelerate/appccelerate#15]
Hi,
I am using the PassiveStateMachine in a website. The state machine context is saved to the database after every cycle.
Every time the event is coming from the browser by the user, i will load the state machine context from the the database, create a new instance of the state machine and set it to the the right step based on the context.

I have some "ExecuteOnEntryParametrized" defined for some steps. My problem is that i do not want those actions to be executed when i load the state machine from the context. i want it to be executed only when the transition is happening and the state is changed.

Any way to tell the Start action not to execute the OnEntry actions?

Noam

**Comment by noamberda** [comment]
Hi,
I have forked the repository and created a version that allows the following
1. ExecuteOnEntry actions now have executeOnStart property that you can define if you want the action to be executed when the state is initialized from a Start method
2. The internal flow has been adopted to support the scenario above
3. All the current test are running fine with the changes above. I have not added new test to check the new flow

Here is the link to the fork
https://github.com/noamberda/appccelerate

Please let me know your thoughts about it.

Noam

**Comment by ursenzler** [comment]
Hi Noam

I have to discuss this with a colleague.
I'm not sure this is a good approach because it makes building a consistent state machine much harder.
I'd prefer a dedicated way to set the state (and all history states) of the state machine.

So instead of having only Initialize(State), maybe there should be Initialize(State) and Restore(State, HistoryStates).

But I need some time to think it through.

Urs

**Comment by danielmarbach** [comment]
Hy Noam,
I just discussed this today with Urs. In my humble opinion I prefer the way Urs described it. We also discussed the following changes:

Introduce some sort of a "serializer/walker" which allows to save the current state and the history states.
Provide a restore method which allows to restore the current state including the history.

Daniel

**Comment by noamberda** [comment]
Hi Urs, Daniel,
I totally agree, As long as you understand the challenge i am facing and having an idea how to solve it, its good enough for me.
For now i have the fork with the minimum changes i added which allow me to continue moving forward. I will be happy to adopt the new architecture you will come up with once it will be ready.

If you continue the discussion within this thread i could then be updated how to progress is going.

Thanks,
Noam

**Comment by ursenzler** [comment]
We could probably extend the interface that is currently used for reporting. Serialization and reporting is quite the same (on an abstract level ;-) ). Of course, we would need to add a way to deserialize.

**Comment by ursenzler** [comment]
I have a prototype available: https://github.com/ursenzler/appccelerate/tree/statemachineserialization

It only allows saving and loading of the current state of a passive state machine at the moment (see commit messages for details and updates).

Feedback welcome.

**Comment by ursenzler** [comment]
pull request available

**Comment by danielmarbach** [comment]
Code reviewed and commented

Am 29.05.2013 um 10:47 schrieb Urs Enzler notifications@github.com:

**Comment by ursenzler** [comment]
available on the alpha nuget feed : https://teamcity.bbv.ch/guestAuth/app/nuget/v1/FeedService.svc

**Comment by ursenzler** [comment]
- [x] docu is still missing

**Comment by ursenzler** [comment]
This feature is release in 1.0.84
