### ISSUE TITLE
Possible Bug in Distributed Event Broker

### ISSUE THREAD

**Issue by marcoerni** [appccelerate/appccelerate#19]
Hi

We are migrating from Appccelerate.DistributedEventBroker version 1.0.44 to version 1.0.84.
When registering the Distributed Extension on the Event Broker we encounter the following exception:
System.InvalidCastException: Unable to cast object of type 'Appccelerate.EventBroker.EventBroker' to type 'Appccelerate.EventBroker.IEventRegistrar'

The following Unit Test repoduces the issue:

```
public class DistributedEventBrokerBugRepro
{
    [Fact]
    public void AddDistributedExtension_MustNotThrow()
    {
        var eventBroker = new EventBroker();
        var extension = new FakeDistributedEventBrokerExtension();

        eventBroker.Invoking(x => x.AddDistributedExtension(extension))
            .ShouldNotThrow();
    }

    private class FakeDistributedEventBrokerExtension : DistributedEventBrokerExtensionBase
    {
        public FakeDistributedEventBrokerExtension()
            : base("DistributedEventBroker", new FakeEventBrokerBus())
        {
        }

        private class FakeEventBrokerBus : IEventBrokerBus
        {
            public void Publish(IEventFired message)
            {
            }
        }
    }
}
```

**Comment by danielmarbach** [comment]
This was caused by an internal refactoring of the event broker. This was not discovered because there are not specs available which actually fully use the distributed event broker. I will try to create a specification which uses an In-Memory event broker bus so that in the future this will not  happen again. Will try to fix it over the weekend

**Comment by danielmarbach** [comment]
This should be fixed by now. I increased the version of the distributed event broker because it has a breaking change for a public API which is used internally

**Comment by ursenzler** [comment]
@danielmarbach do you make the release of the distributed event broker, or should I do it?

**Comment by danielmarbach** [comment]
Happy when you do it! I have not yet finished renaming the tests and remove moq but that is not relevant for the bug fix. Happy if you review the acceptance test also. 

Am 22.06.2013 um 16:56 schrieb Urs Enzler notifications@github.com:

**Comment by ursenzler** [comment]
I pushed all distributed event broker packages to nuget. I couldn't use the normal release procedure due to changes made after the last release without killing our versioning scheme. So let's hope it works %-)

**Comment by marcoerni** [comment]
All works as expected! Thanks for the fast bugfix release!
