### ISSUE TITLE
Response from Firing an event in State Machine

### ISSUE THREAD

**Issue by noamberda** [appccelerate/appccelerate#20]
Hi,
I would like to get you opinion on the following scenario.
Today when we are using the PassiveStateMachine the Fire method does not return any results.

It is important for us to know in run-time the results of the fire method and understand if an event was fired at a wrong state.
1. This will allow us to have visibility over the application that use the State Machine and identified potential bugs. (If you fire event when you are not suppose to it might be a bug).
2. We would like to collect all those mismatch events to some kind of a log to learn more about user behavior of the app.

What is your view on that?
Thanks,
Noam

**Comment by ursenzler** [comment]
Hi Noam

You can register the event TransitionDeclined on the state machine. This event gets fired whenever there is no transition possible for the fired event in the current state.

The event arguments contain the information about the current state and the event.

Does this solve your problem?

Cheers,
Urs

**Comment by noamberda** [comment]
Hi Urs,
That could be a solution for part of my scenario.
We have as well a scenario when the mobile app send a service request that execute an event within the state machine. the mobile app is expecting a response to know if the call was a success. For example, cancel a job and transfer it to another user etc... In this case it might be hard to use the TransitionDeclined as it will be happening in a parallel to the event call.

What about returning some kind of a results from the Fire method that provide a feedback if the event was fired or not.

Noam

**Comment by ursenzler** [comment]
The problem with returning a result for the Fire method is that this does not work when using an ActiveStateMachine. And I want to keep the interfaces of both identical so that they can be interchanged (easier testing of code using an active state machine).
Therefore I still suggest that you use the TransitionDeclined event and set a flag in the handler method that you can check when the Fire call returns and react accordingly.

Urs
