### ISSUE TITLE
Unregister item on EventBroker throws when item is already unregistered or EventBroker is already disposed

### ISSUE THREAD

**Issue by marcoerni** [appccelerate/appccelerate#22]
In the EventBroker version 1.0.44 it was allowed to unregister an item on the EventBroker even the EventBroker was already disposed.

In our software the IoC container disposes the EventBroker automatically when the software is being closed, because the EventBroker implements IDisposable.

Other components in our software get automatically registered on the EventBroker when they are activated (created) through the IoC container and automatically unregistered on the EventBroker when they are deactivated (disposed) either by a software shutdown or an internal dispose because the component is no longer used.

In the new version of the EventBroker 2.0.85, unregistering an item twice (or unregistering it after the EventBroker is being disposed) leads to a NullReferenceException in method Appccelerate.EventBroker.Internals.Registrar.UnregisterPropertyPublications() on the line where the removed publication will be disposed (but no publication is being returned).

The problem is that we could not control the order of the dispose calls (so we can’t tell the IoC container to dispose first the registered items and the EventBroker).

We currently removed the automatic un-registration of the items while the objects are deactivated on the IoC container. In my opinion it should not be a problem, because the EventBroker just holds weak references to the registered items.

So for us it is not really an issue. But eventually you would change the behavior to respond more gracefully than just throwing a NullReferenceException.

Here I have the Unit Tests that reproduces the issue:

```
public class EventBrokerBugRepro
{
    private readonly EventBroker testee;

    public EventBrokerBugRepro()
    {
        this.testee = new EventBroker();
    }

    [Fact]
    public void Unregister_WhenNotRegistered_ShouldNotThrow()
    {
        var component = new Component();

        this.testee.Invoking(x => x.Unregister(component))
            .ShouldNotThrow();
    }

    [Fact]
    public void Unregister_WhenCalledTwice_ShouldNotThrow()
    {
        var component = new Component();

        this.testee.Register(component);
        this.testee.Unregister(component);

        this.testee.Invoking(x => x.Unregister(component))
            .ShouldNotThrow();
    }

    [Fact]
    public void Unregister_WhenEventBrokerIsDisposed_ShouldNotThrow()
    {
        var component = new Component();

        this.testee.Register(component);
        this.testee.Dispose();

        this.testee.Unregister(component);

        this.testee.Invoking(x => x.Unregister(component))
            .ShouldNotThrow();
    }

    public class Component
    {
        private const string Topic = "Topic";

        [EventPublication(Topic)]
        public event EventHandler<EventArgs<Data>> Event;
    }

    public class Data
    {
    }
}
```

**Comment by ursenzler** [comment]
The event broker will remove the weak links when the next event is fired.
I'll look into this issue.

**Comment by ursenzler** [comment]
This is fixed
