### ISSUE TITLE
Condition rules for all events

### ISSUE THREAD

**Issue by noamberda** [appccelerate/appccelerate#23]
Hi,
I would like to add a condition rule for all events. The condition is that a user can execute an event only if he has certain roles.
I though about a way i could add it as part of the standard Event definition.
I wrapped my event enum with a class and implement IComparable. then the idea was to reject the IComparable if the events are not the same (Not same enum value + Does not have the necessary roles).

The problem is that the statemachine compare events based on HashCode and not iComparable. i assume IComparable is for the sorting.
As such i cannot compare the event that was fired to the event that i have in my statemachine schema.

Any proposal?

Noam

PS it is possible to do the above using a guard but then i need to define the guard for each event.

**Comment by ursenzler** [comment]
If it is for all events, then is it possible to check the permission before you even call Fire on the state machine?

**Comment by noamberda** [comment]
Hi Urs,
This is part of a bigger scenario i am working on. let me give you the details.
Based on schema i define for the state machine, i would like know what events can be executed for each action.
I will use this information later in the UI to see what actions a user can execute a certain state.

The idea is that i use the StateMachine schema as the main meta data source. I wanted to include the Role information in the State Machine schema as well.

If i don't use the StateMachine to hold all this data i would need to develop something else to hold the meta data of what event can be executed at each action and then the roles for this event. 

Noam

**Comment by ursenzler** [comment]
You can extract the information about the events that are known for each state by implementing your own IStateMachineReport:

```
public interface IStateMachineReport<TState, TEvent>
    where TState : IComparable
    where TEvent : IComparable
{
    /// <summary>
    /// Generates a report of the state machine.
    /// </summary>
    /// <param name="name">The name of the state machine.</param>
    /// <param name="states">The states.</param>
    /// <param name="initialStateId">The initial state id.</param>
    void Report(string name, IEnumerable<IState<TState, TEvent>> states, Initializable<TState> initialStateId);
}
```

You get access to all knowns states and per state to all transitions. And a transition gives you the event.

You can take a look at the class CsvStateMachineReportGenerator for a kickstart: https://github.com/appccelerate/appccelerate/blob/master/source/Appccelerate.StateMachine/Reports/CsvStateMachineReportGenerator.cs

Call Report on the state machine with your "report"-generator.

Let me know if you need more info.

Happy coding
Urs

**Comment by ursenzler** [comment]
The problem with IComparable is that it would be better if the constraint would be on IEquatable<T>.
But enums do not implement IEquatable, but IComparable. Therefore, I have to use IComparable :-(

**Comment by noamberda** [comment]
I have created a custom Event object, implemented IComparable and it is never called. Only the GetHashCode and Equals are been called. Is this how it suppose to be?

Would it be possible to pass to the guard the TEvent object that was declare before the guard? i would like to create a guard that use some of the data within my TEvent. (I will add the role to the TEvent object and will use it in the guard after.

Noam

**Comment by ursenzler** [comment]
Yes the IComparable is ugly, but the .Net framework does not mark enum as IEquatable<T> (see comment above).

For passing data, it is easier to use the argument you can pass in the Fire method. Then, all guards and actions have access to it. (yes I know, it's not type safe :-( )

**Comment by noamberda** [comment]
Sorry Urs about my English i am not a native English speaker. I hope you still have some patient for my questions :)
I have added a picture to illustrate what i am looking for
As you can see i am declaring an event on my state (Yellow color). At that deceleration i am specifying the event type as well some additional meta data about the role associated to this event.

Then on the guard (The red color) i am receiving the event argument at run-time that i was sending through the Fire method. I would like to receive as well at the delegate the EventMeta object that i was creating when declaring the state. (Please see the second picture how i would like to signature of this delegate to be.)

picture 1
![image](https://f.cloud.github.com/assets/128920/725787/eba84558-e0a4-11e2-8bee-94c23745a08d.png)

picture 2
![image](https://f.cloud.github.com/assets/128920/725795/7d10ffbc-e0a5-11e2-9490-02688dd94671.png)

Sorry for the trouble.

Thanks,
Noam

**Comment by ursenzler** [comment]
Your English is just fine. Neither am I a native English speaker ;-)

What you wish is currently not possible and I don't think that I will change this. Let me explain why.
A guard should not decide on something defined by the event itself. In this case you could use a different event and wouldn't need the guard at all.
To pass data to a guard, use the argument. That's what it is for.
I think this keeps the design simple.

And now to your case. Can't you pass the information you want to access from the event in the argument, too?
I know, the duplication is not super sexy, but your guards could access the needed data.

Just in case you didn't notice. You can define a guard with a generic argument:

```
.On(state)
    .If<MyArgument>(argument => ...)
```

Or even simpler:

```
.On(state)
    If((MyArgument argument) => ...)
```

You get "some type safety" this way. The state machine casts the argument for you.

No trouble at all :-)

**Comment by noamberda** [comment]
Thanks :). 

Appreciate your advice. I will look into that.

As for the IStateMachineReport, i have used it and its working great.

I will close the case for now unless you want to keep it open, maybe you will change you mind ;).

Noam

**Comment by ursenzler** [comment]
Good to hear!
