### ISSUE TITLE
Windows Phone 8 Support

### ISSUE THREAD

**Issue by clauchiorean** [appccelerate/appccelerate#24]
Hi,

I'm using you state machine on a windows phone 8 project.
Till the latest update I could adapt the sources and make them work for WP8 now with the dependency to TPL Dataflow 4.5.9 i can't use the active state machine.

Do you plan to add support for windows phone?

And the same problem is for windows 8.

I saw that you want to make the libraries portable. Any date for a release?

**Comment by ursenzler** [comment]
The latest version in the repo does not use Dataflow anymore. But unfortunately, I didn't remove the reference.
Can you try, when you simply remove the reference on TPPL Dataflow (System.Threading.Tasks.Dataflow)?

I replaced the internal use of the Appccelerate.AsyncModule with TPL components. Therefore the change.

Let me know if it works for you. And I will remove the reference in the repo as soon as possible.

And for the future: we plan to support as many platforms as possible, once we reach a stable version for the next release for our PCL libraries (therefore the switch to PCLs). But currently, we develop only for .Net 4.5 and Windows Store Apps.

Cheers,
Urs

**Comment by ursenzler** [comment]
Hmm, there could be a problem with our usage of the type Missing. How did you handle this in your adapted version?

**Comment by clauchiorean** [comment]
I did not include the ActiveStateMachine in the project, I'm using only the pasive one.
I saw that TPL components are not portable?
Can you use the async apis? Tasks?

http://msdn.microsoft.com/en-us/library/vstudio/hh191443.aspx
http://msdn.microsoft.com/en-us/library/vstudio/system.threading.tasks.aspx

**Comment by ursenzler** [comment]
Sorry, I mixed my fork https://github.com/ursenzler/appccelerate with the main repo. In my fork, Dataflows are not used anymore.

**Comment by ursenzler** [comment]
Can you work with the version from my fork?

Unfortunately, I cannot make the PCL to also support WP8 because I first have to pimp our build environment and because there seams to be a problem with the type Missing when targeting full .Net, Store Apps and WP8 !?!?!?!?

**Comment by clauchiorean** [comment]
I'll give it a try  tomorrow :)

**Comment by ursenzler** [comment]
News?

**Comment by clauchiorean** [comment]
I just created a wp8 library project and added the code and it worked :)

**Comment by ursenzler** [comment]
Good to hear.
We are working on a PCL version that can simply be referenced from a WP8 projects, but we still have some problems with unknown source (types go missing when addign WP8 as a target to the PCL, but the type should be there).
