### ISSUE TITLE
Exception thrown within Execute does not prevent from moving to next state

### ISSUE THREAD

**Issue by noamberda** [appccelerate/appccelerate#29]
Hi,
We have the following scenario
.On(xxxxx)
  .Goto(vvvvv)
  .Execute(zzzzz)

Currently when an exception is thrown within the Execute method the state machine is still moving to the next Goto state.

What should be then the best practice in this case?
I would like to prevent the state machine to move to the next state if execute fail. As well there is no possibility to make a call to execute first and then to Goto.

Thanks,
Noam

**Comment by ursenzler** [comment]
Hi Noam

This behavior is by design. When you fire the event to the state machine, the state machine will perform the transition (as long as it finds a suitable transition).
You should really try to avoid exceptions in any actions. If you want to prevent the transition depending on some validations or checks, then you can use a Guard:

```
.In(state).On(event)
    .If(() => IsValid()).Goto(newState).Execute(() => Action())
    .Otherwise.Execute(() => SorryCannotDoThis())    // when you define no target state, the state machine remains in the last state
```

What is the reason for your exception?

Happy coding
Urs

**Comment by noamberda** [comment]
Hi Urs,
We are in a certain state and then the user try to make a payment. The payment data is then flow as an event on that specific state. We then execute the payment and go to the next stage. If the payment fail then we would like to throw up an exception and hold back the movement to the next state. The exception is flow nicely up but the state machine already moving to the next state which is not what we want. We have many other execution through the state machine, they can throw exceptions as well that the architecture we have put in place.

We are trying to move all the logic and services of our app to be executed from the state machine. This way we can model it better and control the flow of our jobs. 

I am not sure how I can move a payment operation to a guard it some how break the concept of Execute as I will need to move all the logic to the guard.

Can we introduce a new kind of Execute which will be between the Guard and the Goto. This execute will behave like a normal execute but will be able to prevent the state machine to go to the Goto afterwards?

Thanks,
Noam

**Comment by ursenzler** [comment]
Is it possible that you model this scenario with more than one state?
In the action executing the payment you catch the exception. If you get an exception you fire a PaymentNotPossible (or something alike) event, in case of success you fire a PaymentOkay event. And model these two states accordingly in the state machine. This gives you the possibility to act accordingly in the entry actions of the state for success and the state for failure. And it would give you also the information about retry (coming from the failure state).

Chaning the behaviour of the state machine would be tricky and I'm currently not sure about the side-effects.

Let me know if the above solution works for you.

Happy coding
Urs

**Comment by noamberda** [comment]
Hi Urs,
Thanks, i will think about this proposal.

Noam
