### ISSUE TITLE
Null reference when fire event

### ISSUE THREAD

**Issue by Rader** [appccelerate/appccelerate#30]
the statemachine internal var "events" has one element but it's null. When fire event i get null ref exception at: 

private EventInformation<TEvent> GetNextEventToProcess()
{
    EventInformation<TEvent> value = this.events.First.Value;
    this.events.RemoveFirst();
    return value;
}

![image](https://f.cloud.github.com/assets/1228175/900048/ff8f8b3c-fb55-11e2-8157-ea7d521046c7.png)

**Comment by ursenzler** [comment]
Wow, this is strange.

Can you give me some more information, please:
- Version of Appccelerate.StateMachine
- .Net version of your code
- is multi-threading involved?

**Comment by Rader** [comment]
Appccelerate.StateMachine: 1.0.44
.Net : v4.0.30319

yes, we have other 2 threads to fire events in every 3 minutes.

**Comment by ursenzler** [comment]
The PassiveStateMachine is not thread-safe. You can either switch to the ActiveStateMachine, which is thread-safe, or make sure that you synchronize the calls to the state machine.

**Comment by Rader** [comment]
Thank you, i will try. What's your suggestion for choosing active or passive state machine?

**Comment by danielmarbach** [comment]
If you need your transition actions executed on another thread then you should use ActiveStateMachine. Otherwise Passive

**Comment by ursenzler** [comment]
Or if you call the state machine from different threads, then you should use the active state machine, too.
The active state machine will not block these threads. With the passive state machine, you'll have to implement your own synchronization/locking mechanism.

**Comment by Rader** [comment]
If i am using ActiveStatemachine and define this:

stateMachine.In(someState)
    .On(Trigger.A).Goto(stateA)
        .Execute(DoTaskA1)
        .Execute(DoTaskA2)
    .On(Trigger.B).Goto(stateB)
        .Execute(DoTaskB1)
        .Execute(DoTaskB2)

If Trigger.A is fired, will the actions DoTaskA1 and DoTaskA2 be executed in sequence or concurrently?

**Comment by ursenzler** [comment]
They will be executed in sequence. The active state machine has one worker thread.

**Comment by danielmarbach** [comment]
In sequence

Am 05.08.2013 um 11:23 schrieb Rader notifications@github.com:
